### ISSUE TITLE
Zed Extension

### ISSUE THREAD

**Issue by bbb651** [crisidev/bacon-ls#1]
Thank you for creating this language server!

I've made an [attempt at creating an extension](https://github.com/bbb651/zed-bacon) (currently it only tries to downloads `bacon-ls` if needed and expects `bacon` to be installed), I got to the point that it downloads it correctly, I feel like I'm really close, but I'm getting:
```log
2024-10-02T23:25:21.903509506+03:00 [WARN] request completed with error: failed to connect to the server
```
and debugging extensions in Zed is not great at the moment, I would love some help if your interested and have the time. Also it would be nice to provide `x86` binaries in releases, I don't personally use them but the Zed extension api has it as an option (It might only relevant for windows?) and it currently errors out in that case.
Upstream issue about bacon: https://github.com/zed-industries/zed/issues/15912

**Comment by bbb651** [comment]
I meant x86 as in 32-bit x86, I'm aware the releases contain x86_64 and aarch64 binaries, sorry I wasn't clear.

Extension in Zed don't yet have great documentation, they're mostly copied and modified from each other (this one is based from the zig one). This is my first time writing an extension (although I've contributed to some a bit), I'll try to debug it more or ask for help on the Zed discord. In theory everything all lsp related errors things are reported in the log, but a lot of errors are not very helpful (like this one).

**Comment by crisidev** [comment]
Oh, ok, I can change the build system to also build for 32bit x86. Would you like Linux and windows binaries?

**Comment by crisidev** [comment]
Added i686 linux and windows: https://github.com/crisidev/bacon-ls/commit/638a7213744309f5bc5c75ea88269b72b81c1319

I'll try to kick off a new release build

**Comment by crisidev** [comment]
Github action run: https://github.com/crisidev/bacon-ls/actions/runs/11290889318

**Comment by crisidev** [comment]
It did not work, we need i686 libraries

**Comment by crisidev** [comment]
Potential fix: https://github.com/crisidev/bacon-ls/commit/a606df65b1ef26d034f25f76be3bbe50304e4700

**Comment by crisidev** [comment]
The release is taking ages on Mac builds: https://github.com/crisidev/bacon-ls/actions/runs/11291016153

**Comment by crisidev** [comment]
I think the problem was that I was using very old Macos runner types. I have fixed it now, let's see if this works: https://github.com/crisidev/bacon-ls/actions/runs/11401158335

**Comment by crisidev** [comment]
Finally the release succeeded and we now have i686 builds: https://github.com/crisidev/bacon-ls/releases/tag/v0.3.1
